DELETE http://localhost:3001/api/persons/2

###
GET http://localhost:3001/api/persons/2

###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Meeee",
    "number": "1234"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "1234"
}
